/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import DTO.*;
import BLL.*;

/**
 *
 * @author ACER
 */
public class XemThongTin extends javax.swing.JPanel {

     
    private String sdttmp;
    private String passtmp;
    
    private String ma;
    private String ho;
    private String ten;
    private String gioitinh;
    private String ngaysinh;
    private String chucvu;
    private String luong;
    private nhanVien nv;
    private user user;
    
    NhanVienBLL nvBLL = new NhanVienBLL(null);
    UserBLL userBLL = new UserBLL();
    
    public XemThongTin() {
        initComponents();
       
        
        ma_nv.setEditable(false);
        ho_nv.setEditable(false);
        ten_nv.setEditable(false);
        gioitinh_nv.setEditable(false);
        sdt_nv.setEditable(false);
        ngaysinh_nv.setEditable(false);
        chucvu_nv.setEditable(false);
        luong_nv.setEditable(false);
        pass_nv.setEditable(false);
        
        
        btn_xacnhan_sdt.setEnabled(false);
        btn_xacnhan_pass.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ma_nv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ho_nv = new javax.swing.JTextField();
        ten_nv = new javax.swing.JTextField();
        gioitinh_nv = new javax.swing.JTextField();
        sdt_nv = new javax.swing.JTextField();
        ngaysinh_nv = new javax.swing.JTextField();
        chucvu_nv = new javax.swing.JTextField();
        luong_nv = new javax.swing.JTextField();
        pass_nv = new javax.swing.JPasswordField();
        btn_sua_pass = new javax.swing.JButton();
        btn_sua_sdt = new javax.swing.JButton();
        xemPass = new javax.swing.JCheckBox();
        btn_xacnhan_sdt = new javax.swing.JButton();
        btn_xacnhan_pass = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông Tin Tài Khoản");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Mã nhân viên:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Họ nhân viên:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Tên nhân viên:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Giới tính:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Số điện thoại:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Ngày sinh:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Chức vụ:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Lương:");

        ma_nv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Mật khẩu:");

        ho_nv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ten_nv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        gioitinh_nv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        sdt_nv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ngaysinh_nv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        chucvu_nv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        luong_nv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pass_nv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_sua_pass.setText("Đổi");
        btn_sua_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sua_passActionPerformed(evt);
            }
        });

        btn_sua_sdt.setText("Đổi");
        btn_sua_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sua_sdtActionPerformed(evt);
            }
        });

        xemPass.setText("Xem mật khẩu");
        xemPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemPassActionPerformed(evt);
            }
        });

        btn_xacnhan_sdt.setText("Xác nhận");
        btn_xacnhan_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacnhan_sdtActionPerformed(evt);
            }
        });

        btn_xacnhan_pass.setText("Xác nhận");
        btn_xacnhan_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacnhan_passActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ho_nv)
                                    .addComponent(ten_nv)
                                    .addComponent(gioitinh_nv)
                                    .addComponent(sdt_nv)
                                    .addComponent(ngaysinh_nv)
                                    .addComponent(chucvu_nv)
                                    .addComponent(luong_nv)
                                    .addComponent(pass_nv)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ma_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_sua_sdt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_xacnhan_sdt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_sua_pass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_xacnhan_pass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xemPass)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ma_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ho_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ten_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gioitinh_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sdt_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua_sdt)
                    .addComponent(btn_xacnhan_sdt))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ngaysinh_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chucvu_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(luong_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pass_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua_pass)
                    .addComponent(xemPass)
                    .addComponent(btn_xacnhan_pass))
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xemPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemPassActionPerformed
         if(xemPass.isSelected()) {
            pass_nv.setEchoChar((char)0);
        } else {
            pass_nv.setEchoChar('*');
        }
    }//GEN-LAST:event_xemPassActionPerformed

    private void btn_sua_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sua_sdtActionPerformed
        ma = ma_nv.getText();
        ho = ho_nv.getText();
        ten = ten_nv.getText();
        gioitinh = gioitinh_nv.getText();
        ngaysinh = ngaysinh_nv.getText();
        chucvu = chucvu_nv.getText();
        luong = luong_nv.getText();
        
        
        sdt_nv.setEditable(true);
        sdt_nv.grabFocus();
        btn_sua_sdt.setEnabled(false);
        btn_xacnhan_sdt.setEnabled(true);
        sdttmp = sdt_nv.getText();
    }//GEN-LAST:event_btn_sua_sdtActionPerformed

    private void btn_sua_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sua_passActionPerformed
        ma = ma_nv.getText();
        
        pass_nv.setEditable(true);
        pass_nv.grabFocus();
        btn_xacnhan_pass.setEnabled(true);
        passtmp = pass_nv.getText();
    }//GEN-LAST:event_btn_sua_passActionPerformed

    private void btn_xacnhan_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacnhan_sdtActionPerformed
        String sdt = sdt_nv.getText().trim();
        if (sdttmp.equals(sdt)) {
            int confirm = JOptionPane.showConfirmDialog(this, "Số điện thoại không có thay đổi, bạn có muốn tiếp tục ?");
            if (confirm == JOptionPane.YES_OPTION) {
                return;
            } else {
                btn_xacnhan_sdt.setEnabled(false);
                btn_sua_sdt.setEnabled(true);
                return;
            }
        }

        if (!sdt.matches("^0\\d{9}$")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ");
            return;
        }

        try {
            Long luongl = Long.valueOf(luong);
            nv = new nhanVien(ma, ho, ten, gioitinh, sdt, ngaysinh, chucvu, luongl);
            nvBLL.update(nv, ma);
            btn_xacnhan_sdt.setEnabled(false);
            btn_sua_sdt.setEnabled(true);
            sdt_nv.setText(sdt);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_xacnhan_sdtActionPerformed

    private void btn_xacnhan_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacnhan_passActionPerformed
        String password = pass_nv.getText().trim();
        
        if (passtmp.equals(password)) {
            int confirm = JOptionPane.showConfirmDialog(this, "Mật khẩu không có thay đổi, bạn có muốn tiếp tục ?");
            if (confirm == JOptionPane.YES_OPTION) {
                return;
            } else {
                btn_xacnhan_pass.setEnabled(false);
                btn_sua_pass.setEnabled(true);
                return;
            }
        }
        
        try {
            user = new user(ma, password);
            userBLL.update(user, ma);
            btn_xacnhan_pass.setEnabled(false);
            btn_sua_pass.setEnabled(true);
            pass_nv.setText(password);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_xacnhan_passActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua_pass;
    private javax.swing.JButton btn_sua_sdt;
    public javax.swing.JButton btn_xacnhan_pass;
    public javax.swing.JButton btn_xacnhan_sdt;
    public javax.swing.JTextField chucvu_nv;
    public javax.swing.JTextField gioitinh_nv;
    public javax.swing.JTextField ho_nv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField luong_nv;
    public javax.swing.JTextField ma_nv;
    public javax.swing.JTextField ngaysinh_nv;
    public javax.swing.JPasswordField pass_nv;
    public javax.swing.JTextField sdt_nv;
    public javax.swing.JTextField ten_nv;
    private javax.swing.JCheckBox xemPass;
    // End of variables declaration//GEN-END:variables
}
